### ISSUE TITLE
Persist Budget

### ISSUE THREAD

**Issue by leo-benz** [leo-benz/budgetbudget-native#28]
The values entered to the budgeted field shall be persisted across application launches.

**Comment by Xiphe** [comment]
Do you plan compatibility with the current format? (`json` with `.budget` extension).

I can specify the current structure and my thoughts behind that if that helps.

**Comment by leo-benz** [comment]
I am not sure about it yet. Probably trying to ensure compatibility will increase complexity compared to built in swift serialisation methods. Especially also when thinking about future implementations of iCloud Sync. 

Importing budgets from the current format is definitely a must have.

**Comment by Xiphe** [comment]
Makes sense 👍

**Comment by leo-benz** [comment]
Follow up for importing existing budgets in #32
