### ISSUE TITLE
Next steps

### ISSUE THREAD

**Issue by Xiphe** [leo-benz/budgetbudget-native#39]
Hey @leo-benz and @d12bb 

First of all: Sorry that I have not been able to chime in here in the past and that the whole BB dev has been stagnant from my end!

As of late I decided to re-orientate job-wise which will hopefully provide me some space again to work on BB and with that I would like to change the direction a bit.

1. I would still like to rebuild BB as a native app with a bunch of additional features
2. I have a partner on board who will care for making the app visible to the public, help with website, FAQ, etc.
3. We want to charge a one-time fee of ~10€ for it (similar to how MM costs some money upfront) [no recurring fees, those suck]
4. I probably won't do it open source
5. In order to understand and "own" everything I would start fresh and not re-use any of the code in here

This path feels right for me, but at the same time feels like disrespecting your work here as well as being unaligned with the small but lovely community that had formed around BudgetBudget. 

Thats why I wanted to be really transparent with all of this. Also I have not started with anything yet – when you have strong feelings or opinions about this: Let's definitely talk!

I hope you're all great! 
Cheers ☀️

**Comment by diktomat** [comment]
Unfortunately this one is asleep for quite some time now, and at least on my part that's highly unlikely to change in the foreseeable future. Therefore I not only have no hard feelings about you starting anew the way you describe it above, I very much would welcome it. 👍

**Comment by Xiphe** [comment]
@d12bb that's great to hear <3 thank you for the feedback

**Comment by leo-benz** [comment]
@Xiphe First of all thanks for reaching out and being open about this. Unfortunately, I haven't had the time or drive to get this project off the ground, and I don't see this changing soon. I still use the original BudgetBudget and would love a native version, especially one compatible with iPadOS.

Given the sensitive nature of financial data, using a closed-source indie apps make me think twice. Open source offers the benefit for auditing the security and data privacy and the possibility to fix potential issues myself several years down the road.

That said I don't have any hard feelings and if that's what BudgetBudget needs to get a fresh breath of life I am all in for it. I'd love to stay close to the project and if you ever have a need for beta testing, feature brainstorming, UX testing, ... please reach out :)

**Comment by Xiphe** [comment]
Thank you for the feedback @leo-benz! That's great to hear! Opposing to what you had planned with this project I will be focusing on a Mac-only successor of the current electron app. 

Extending to a standalone, iOS compatible version that is independent of MoneyMoney is something I have on my mind but it's definitely more in the unknown realm.

Despite the closed source tendency I plan to be transparent with the development and will definitely include you and the other early adopters of the current version in the road ahead!

Cheers 👍
